<$PF9/$objtype/mkfile

LIB=$PF9/$objtype/lib/libString.a

OFILES=\
	s_alloc.$O\
	s_append.$O\
	s_array.$O\
	s_copy.$O\
	s_getline.$O\
	s_grow.$O\
	s_memappend.$O\
	s_nappend.$O\
	s_parse.$O\
	s_putc.$O\
	s_rdinstack.$O\
	s_read.$O\
	s_read_line.$O\
	s_reset.$O\
	s_terminate.$O\
	s_tolower.$O\
	s_unique.$O\

HFILES=$PF9/include/libString.h

<$PF9/src/mksyslib
