<$PF9/$objtype/mkfile

TARG=plumber plumb

BIN=/$objtype/bin
<$PF9/src/mkmany

PLUMBER=plumber.$O fsys.$O match.$O rules.$O
PLUMB=plumb.$O

$PLUMBER:	$HFILES plumber.h
$PLUMB:		$HFILES

$O.plumb:	$PLUMB
$O.plumber:	$PLUMBER

