<$PF9/$objtype/mkfile

TARG=pic
OFILES=picy.$O\
	picl.$O\
	main.$O\
	print.$O\
	misc.$O\
	symtab.$O\
	blockgen.$O\
	boxgen.$O\
	circgen.$O\
	arcgen.$O\
	linegen.$O\
	movegen.$O\
	textgen.$O\
	input.$O\
	for.$O\
	pltroff.$O\

HFILES=pic.h\
	y.tab.h\

YFILES=picy.y\

BIN=/$objtype/bin
<$PF9/src/mkone
YFLAGS=-S -d

picy.c:	y.tab.c
	mv $prereq $target

picl.c:D: picl.lx
	$LEX -9 -t $prereq > $target

clean:V: clean-pic

clean-pic:V:
	rm -f picy.c picl.c
