<$PF9/$objtype/mkfile

LIB=$PF9/$objtype/lib/lib9pclient.a

OFILES=\
	access.$O\
	auth.$O\
	close.$O\
	create.$O\
	dirread.$O\
	fs.$O\
	ns.$O\
	open.$O\
	openfd.$O\
	print.$O\
	read.$O\
	remove.$O\
	seek.$O\
	stat.$O\
	walk.$O\
	write.$O\
	wstat.$O\

HFILES=\
	$PLAN9/include/9pclient.h\
	$PLAN9/include/mux.h\

<$PF9/src/mksyslib
