<$PF9/$objtype/mkfile

TARG=acme
DIRS=mail

OFILES=\
	acme.$O\
	addr.$O\
	buff.$O\
	cols.$O\
	disk.$O\
	ecmd.$O\
	edit.$O\
	elog.$O\
	exec.$O\
	file.$O\
	fsys.$O\
	look.$O\
	regx.$O\
	rows.$O\
	scrl.$O\
	text.$O\
	time.$O\
	util.$O\
	wind.$O\
	xfid.$O\

HFILES=dat.h\
	edit.h\
	fns.h\

BIN=/$objtype/bin
<$PF9/src/mkone
<$PF9/src/mkdirs

edit.$O ecmd.$O elog.$O:	edit.h
