<$PF9/$objtype/mkfile

TARG=sam
SYSOFILES=`{sh ./sysofiles.sh}
OFILES=sam.$O\
	address.$O\
	buff.$O\
	cmd.$O\
	disk.$O\
	error.$O\
	file.$O\
	io.$O\
	list.$O\
	mesg.$O\
	moveto.$O\
	multi.$O\
	rasp.$O\
	regexp.$O\
	shell.$O\
	string.$O\
	sys.$O\
	$SYSOFILES\
	util.$O\
	xec.$O\

HFILES=sam.h\
	errors.h\
	mesg.h\


BIN=/$objtype/bin
<$PF9/src/mkone
