<$PF9/$objtype/mkfile

BUGGERED='fs|fmt|utf'
LIBDIRS=`ls -ld lib* | sed -n 's/^d.* //p' |egrep -v "^lib($BUGGERED)$"`

DIRS=\
	$LIBDIRS\
	cmd\


all:V: pf9-prereq
<$PF9/src/mkdirs

pf9-prereq:V:
	objtype=$cputype
	mk -f mkfile.prereq

#nuke:V:
#	mk -f mkfile.prereq nuke

