<$PF9/$objtype/mkfile

# Calling this grep breaks a LOT.  Like egrep on Linux.
# And probably configure.

TARG=grep
HFILES=\
	grep.h\

OFILES=\
	y.tab.$O\
	main.$O\
	comp.$O\
	sub.$O\

YFILES=grep.y\

BIN=/$objtype/bin
<$PF9/src/mkone
